### PR TITLE
fix(logger): Fixed `fc` is nil

### PR DESCRIPTION
**Pull request by flc1125**
- [x] Do only one thing
- [x] Non breaking API changes
- [ ] Tested

### CODE REVIEW

**Review by shedyfreak — APPROVED** [review]
lftm, although I would suggest 
l.Printf(l.traceWarnStr, utils.FileWithLineNum(), err, float64(elapsed.Nanoseconds())/1e6, "-", "-")
before returning

**Comment by flc1125** [comment]
> lftm, although I would suggest l.Printf(l.traceWarnStr, utils.FileWithLineNum(), err, float64(elapsed.Nanoseconds())/1e6, "-", "-") before returning

If I return from there, I have code snippets of my switch, almost every one of them, will that cause redundant confusion.

**Comment by jinzhu** [comment]
Can you let me know why this is needed? in which cases the `fc` will be nil when using GORM.

**Comment by flc1125** [comment]
> Can you let me know why this is needed? in which cases the `fc` will be nil when using GORM.

I was writing unit tests when I discovered the problem and fixed it together.

**Comment by jinzhu** [comment]
If we can't reproduce this when using GORM's API directly, I think it is safe to keep it now to avoid unnecessary condition check.

Thank you.

**Pull request closed without merging**
