### PR TITLE
Nested transaction support via savepoint

### PR DESCRIPTION
**Pull request by nanjj**
Make sure these boxes checked before submitting your pull request.

- [x] Do only one thing
- [x] No API-breaking changes
- [x] New code/logic commented & tested

For significant changes like big bug fixes, new features, please open an issue to make an agreement on an implementation design/plan first before starting it.

### What did this pull request do?
Support simulated nested transaction via savepoint

### CODE REVIEW

**Comment by nanjj** [comment]
recheck

**Comment by EdmundLeex** [comment]
Any plan merging this?

**Comment by nicowolf91** [comment]
Will this be merged any time soon?

**Comment by olgtd** [comment]
will merge it sonn?

**Comment by flyfy1** [comment]
Really looking forward for this MR to get merged

**Pull request closed without merging**
