### PR TITLE
Add with clause support

### PR DESCRIPTION
**Pull request by kvii**
- [x] Do only one thing
- [x] Non breaking API changes
- [x] Tested

### What did this pull request do?

Add WITH and WITH RECURSIVE support.
Modify clause.With and add WithExpression.
All code added in package clause are tested.
All edge case on DB.With are tested manually, see details below.

在 gorm 包内添加了 With 和 Recursive 两个 api 用于支持 with 查询。
在 clause 包内补充了 With clause 并且添加了 WithExpression expression。
clause 包代码已维护测试代码。
gorm 包代码的所有边界情况都经过手工测试，详见下方说明。

### User Case Description

``` go
// good cases
// db = db.With("cte", "SELECT id, `name` FROM users")
// db = db.With("cte", gorm.Expr("SELECT id, `name` FROM users"))
// db = db.With("cte", db.Select("id", "name").Table("users"))
// db = db.With("cte", "id", "name", "SELECT id, `name` FROM users")
// db = db.With("cte", "id, name", "SELECT id, `name` FROM users")
// db = db.With("cte", []string{"id", "name"}, "SELECT id, `name` FROM users")

// error cases
// db = db.With("cte")
// db = db.With("cte", "a", "b,c", "select 1,2,3")
// db = db.With("cte", "a", 2, "select 1,2")
// db = db.With("cte", []string{"a", "b,c"}, "select 1,2,3")
// db = db.With("cte", 1, "select 1")
// db = db.With("cte", []string{"a"})
// db = db.With("cte", []string{"a"}, "b", "SELECT 1, 2")

db = db.With("cte", "id", "name", "SELECT id, `name` FROM users")
db = db.Table("cte")
db = db.Find(&users)
// WITH `cte` (`id`,`name`) AS (SELECT id, `name` FROM users) SELECT * FROM `cte`
```

### CODE REVIEW

**Comment by kvii** [comment]
I have read this issue #3955.
And I know I can use `db.Clauses` to add custom clauses.
But I think it's necessary to add WITH clause even it not supported in old SQL version.
And I saw an empty struct in with.go called With.
With clause is useful when you need a recursive query.
For example, an employ table.

Here is an example to show how to query the sum of 1+2...+n.

我读过这个 issue #3955
也知道可以用 db.Clause 去添加自定义子句。
但我认为 With clause 也是可以添加的。
况且在 clause/with.go 那里也有一个名字叫 With 的空 struct。
在一些有父子关系的表格中，With 语句在递归查询方面的帮助还挺大的。
我写了一个例子，使用 with 语句，已递归的方式查询等差数列的和。

``` go
var n int
db = db.Recursive("cte", "i", "n", fn(db))
db = db.Select("n")
db = db.Table("cte")
db = db.Where("i = ?", 10)
db = db.Take(&n)
fmt.Println(n) // 55

// WITH RECURSIVE `cte` (`i`,`n`) AS (SELECT 1,1 UNION ALL SELECT i+1,n+i+1 FROM `cte` WHERE cte.i < 10)
// SELECT n FROM `cte` WHERE i = 10 LIMIT 1

func fn(tx *gorm.DB) *gorm.DB {
  db := tx.Select("i+1", "n+i+1")
  db = db.Table("cte")
  db = db.Where("cte.i < 10")
  return tx.Raw("SELECT 1,1 UNION ALL ?", db)
}
```

**Comment by d-baranowski** [comment]
Closed but not merged?

**Comment by kvii** [comment]
It was closed by myself.

**Comment by kvii** [comment]
https://github.com/go-gorm/gorm/pull/5161#issuecomment-1154799735
It was closed by myself.

**Comment by d-baranowski** [comment]
:( Can I still get something like this working without this PR in place? I reckon I need to write a custom close similar to the one in `clause/with.go` but will it still work without other changes?

**Pull request closed without merging**
