### PR TITLE
refactor(scan.go): array index is out of bounds exits the for loop

### PR DESCRIPTION
**Pull request by demoManito**
- [x] Do only one thing
- [x] Non breaking API changes
- [x] Tested

### What did this pull request do?

传入的是数组，返回的行数超过数组长度，结束当前的扫描

array is passed in, and the number of rows returned exceeds the length of the array, ending the current scan.

### CODE REVIEW

**Comment by jinzhu** [comment]
Hi @demoManito 

Thank you for your PR, can you add some tests?

**Comment by demoManito** [comment]
> Hi @demoManito
> 
> Thank you for your PR, can you add some tests?

done @jinzhu

**Comment by demoManito** [comment]
> Hi @demoManito
> 
> Thank you for your PR, can you add some tests?

done @jinzhu

**Comment by jinzhu** [comment]
tests pass w/o those changes?

**Comment by jinzhu** [comment]
> tests pass w/o those changes?

Ah, apologies for the oversight on my part regarding the pull request.

It appears this submission is aimed at refactoring rather than bug fixing.

Nonetheless, considering the usage of array types tends to be an edge case, maintaining the existing approach might be preferable to avoid introducing extra checks for most scenarios.

Thank you anyway.

**Comment by demoManito** [comment]
> > tests pass w/o those changes?
> 
> Ah, apologies for the oversight on my part regarding the pull request.
> 
> It appears this submission is aimed at refactoring rather than bug fixing.
> 
> Nonetheless, considering the usage of array types tends to be an edge case, maintaining the existing approach might be preferable to avoid introducing extra checks for most scenarios.
> 
> Thank you anyway.

Okay, I understand

**Pull request closed without merging**
