### PR TITLE
temporary fix ci

### PR DESCRIPTION
**Pull request by black-06**
- [X] Do only one thing
- [X] Non breaking API changes
- [X] Tested

### What did this pull request do?

just a temporary fix, when we merge the #6822, this part needs to be rollback.

### CODE REVIEW

**Review by saeidee — APPROVED** [review]

**Comment by saeidee** [comment]
> * [x]  Do only one thing
> * [x]  Non breaking API changes
> * [x]  Tested
> 
> ### What did this pull request do?
> just a temporary fix, when we merge the #6822, this part needs to be rollback.
> 
> ### User Case Description

Could you please merge this and remove it from your PR(https://github.com/go-gorm/gorm/pull/6822).

**Comment by black-06** [comment]
> Could you please merge this and remove it from your PR(https://github.com/go-gorm/gorm/pull/6822).

Usually @jinzhu does this action, and he has the final decision-making power

**Comment by jinzhu** [comment]
Having a broken CI broken is acceptable as long as we haven't released a new version yet.

Let's fix the tests for each driver first.

**Comment by jinzhu** [comment]
> Usually @jinzhu does this action, and he has the final decision-making power

Any maintainer can merge PRs, this is your right and responsibility ;)

I'm fine with it as long as it doesn't break anything and won't break in the near future. 

Anyway, if anything is unclear, always good to @ me, and I'll check it out as soon as I have time

**Pull request closed without merging**
