### PR TITLE
finisher_app.go Add ExecRaw Method.

### PR DESCRIPTION
**Pull request by piyongcai**
- [x] Do only one thing
- [x] Non breaking API changes
- [x] Tested

### What did this pull request do?

im some time, you need to exe
finisher_app.go Add ExecRaw Method.
it use
** Do no processing and execute the original sql **

Sometimes you execute some super complex SQL statements that cannot be done with gorm or even with gorm.Raw . eg:
```sql
with idx as (
    select ('{' || odr.idx-1 || ',sub_orders,' || subOdr.idx-1 || '}')::text[] as path
      from (
        select idx, data->'sub_orders' as sub_orders
          from user_orders, jsonb_array_elements(orders) with ordinality as odr(data, idx)
         where user_id=$1 and jsonb_path_exists(data,'$ ? (@[*].id==1)')
     ) odr, jsonb_array_elements(sub_orders) with ordinality as subOdr(data, idx)
    where jsonb_path_exists(data,'$ ? (@.id==11)')
)
UPDATE user_orders
   SET orders=jsonb_set(orders, idx.path, $2, false)
  FROM idx
 WHERE user_id=$3
```

### User Case Description

```go
func main() {        
    
	type UserOrder struct {
		ID        int64
		UserID in64
                Orders datatypes.JSON `gorm:"type:jsonb"`
	}

	db, err := gorm.Open(postgres.New(postgres.Config{
		DSN: `dsn`,
		PreferSimpleProtocol: false,
	}), &gorm.Config{
		Logger:                 logger.Default.LogMode(logger.Info),
		SkipDefaultTransaction: true,
	})
	if err != nil {
		log.Fatal(err)
	}

       uo ：= &UserOrder{
                 UserID :1,
                 Orders: datatypes.JSON(`
[
    {
        "id": 1,
        "sub_orders": [
            {
                "id": 11,
                "remark":"this is a remark"
            }
        ]
    }
]`)
        }

	if err := db.AutoMigrate(&UserOrder{}); err != nil {
		t.Fatal(err)
	}

	if err := db.Create(al).Error; err != nil {
		t.Fatal(err)
	}

        err:=db.ExecRaw(`with idx as (
    select ('{' || odr.idx-1 || ',sub_orders,' || subOdr.idx-1 || '}')::text[] as path
      from (
        select idx, data->'sub_orders' as sub_orders
          from user_orders, jsonb_array_elements(orders) with ordinality as odr(data, idx)
         where user_id=$1 and jsonb_path_exists(data,'$ ? (@[*].id==1)')
     ) odr, jsonb_array_elements(sub_orders) with ordinality as subOdr(data, idx)
    where jsonb_path_exists(data,'$ ? (@.id==11)')
)
UPDATE user_orders
   SET orders=jsonb_set(orders, idx.path, $2, false)
  FROM idx
 WHERE user_id=$3`,1,'{"id":1,"remark":"remark changed"}')

      if err != nil {
		t.Fatal(err)
	}
    .......

}
```

### CODE REVIEW

**Comment by li-jin-gou** [comment]
hello, Why not use `DB.Exec`  ?

**Comment by jinzhu** [comment]
Thank you for your PR, but not going to accept it.

If this is needed, maybe just use the generic DB for the job. 

Thank you. https://gorm.io/docs/generic_interface.html

**Comment by piyongcai** [comment]
> hello, why not use `DB.Exec` ? 🙃

because db.Exec will set '?' as  a paramter and set '@' as named paramter.  but the follow sql, the '?' and '@' is the raw sql  symbol.
```sql
with idx as (
    select ('{' || odr.idx-1 || ',sub_orders,' || subOdr.idx-1 || '}')::text[] as path
      from (
        select idx, data->'sub_orders' as sub_orders
          from user_orders, jsonb_array_elements(orders) with ordinality as odr(data, idx)
         where user_id=$1 and jsonb_path_exists(data,'$                                              ? (@[*].id==1)')
     ) odr, jsonb_array_elements(sub_orders) with ordinality as subOdr(data, idx)
    where jsonb_path_exists(data,'$ ? (                                       @.id==11)')
)
UPDATE user_orders
   SET orders=jsonb_set(orders, idx.path, $2, false)
  FROM idx
 WHERE user_id=$3
```

**Comment by piyongcai** [comment]
@jinzhu @li-jin-gou

**Comment by piyongcai** [comment]
> Thank you for your PR, but not going to accept it.
> 
> If this is needed, maybe just use the generic DB for the job.
> 
> Thank you. https://gorm.io/docs/generic_interface.html

because db.Exec will set '?' as  a paramter and set '@' as named paramter.  but the follow sql, the '?' and '@' is the raw sql  symbol.
```sql
with idx as (
    select ('{' || odr.idx-1 || ',sub_orders,' || subOdr.idx-1 || '}')::text[] as path
      from (
        select idx, data->'sub_orders' as sub_orders
          from user_orders, jsonb_array_elements(orders) with ordinality as odr(data, idx)
         where user_id=$1 and jsonb_path_exists(data,'$                                              ? (@[*].id==1)')
     ) odr, jsonb_array_elements(sub_orders) with ordinality as subOdr(data, idx)
    where jsonb_path_exists(data,'$ ? (                                       @.id==11)')
)
UPDATE user_orders
   SET orders=jsonb_set(orders, idx.path, $2, false)
  FROM idx
 WHERE user_id=$3
```

**Pull request closed without merging**
