### PR TITLE
Tag `default` leads to the error `Error 1110: Column specified twice`…

### LINKED ISSUE #3670: Tag default:0 leads to error  Column specified twice
Hello, I think I found a bug but when I try to solve it I can't fully understand how it work.

I create struct model with default value in gorm tag like this

type PurchaseTransaction struct {
	PurchaseID            uint64                 `json:"purchase_id" gorm:"column:purchase_id;type:BIGINT(32);not null;primary_key;default:0;"`
	ReserveId             uint64                 `json:"reserve_id" gorm:"column:reserve_id;type:BIGINT(32);"`
	MerchantReserveID     uint64                 `json:"merchant_reserve_id" gorm:"column:merchant_reserve_id;type:BIGINT(32);"`
	MerchantCustomerCode  string                 `json:"merchant_customer_code" gorm:"column:merchant_customer_code;type:varchar(100);"`
	DomainID              uint64                 `json:"domain_id" gorm:"column:domain_id;type:BIGINT(32);"`
	CustomerId            string                 `json:"cust_id" gorm:"column:cust_id;type:varchar(60);"`
	Amount                float64                `json:"amount" gorm:"column:amount;type:decimal(13,4);"`
	CreationDateUTC       time.Time              `json:"creation_date_utc" gorm:"column:creation_date_utc;type:datetime;"`
	CurrentBalance        float64                `json:"current_balance" gorm:"column:current_balance;type:decimal(13,4);"`
	SeqNum                uint64                 `json:"seq_num" gorm:"column:seq_num;type:BIGINT(32);"`
	CurrentStatus         btienum.PurchaseStatus `json:"current_status" gorm:"column:current_status;type:enum('Opened', 'Closed');"`
	NumberOfLines         int                    `json:"number_of_lines" gorm:"column:number_of_lines;type:int;"`
	NumberOfOpenLines     int                    `json:"number_of_open_lines" gorm:"column:number_of_open_lines;type:int;"`
	NumberOfSettledLines  int                    `json:"number_of_settled_lines" gorm:"column:number_of_settled_lines;type:int;"`
	NumberOfLostLines     int                    `json:"number_of_lost_lines" gorm:"column:number_of_lost_lines;type:int;"`
	NumberOfWonLines      int                    `json:"number_of_won_lines" gorm:"column:number_of_won_lines;type:int;"`
	NumberOfCanceledLines int                    `json:"number_of_canceled_lines" gorm:"column:number_of_canceled_lines;type:int;"`
	NumberOfDrawLines     int                    `json:"number_of_draw_lines" gorm:"column:number_of_draw_lines;type:int;"`
	NumberOfCashOutLines  int                    `json:"number_of_cash_out_lines" gorm:"column:number_of_cash_out_lines;type:int;"`
	ExtBonusContribution  float64                `json:"ext_bonus_contribution" gorm:"column:ext_bonus_contribution;type:decimal(13,4);"`
}

If you see my primary key "purchase_id", it will set default value to 0. When I run func create with this model, it will leaded to this error.

 INSERT INTO `bti_purchase_transaction` (`purchase_id`,`reserve_id`,`merchant_reserve_id`,`merchant_customer_code`,`domain_id`,`cust_id`,`amount`,`creation_date_utc`,`current_balance`,`seq_num`,`current_status`,`number_of_lines`,`number_of_open_lines`,`number_of_settled_lines`,`number_of_lost_lines`,`number_of_won_lines`,`number_of_canceled_lines`,`number_of_draw_lines`,`number_of_cash_out_lines`,`ext_bonus_contribution`,`purchase_id`) VALUES (345678,0,0,'',0,'',0.000000,'0000-00-00 00:00:00',0.000000,0,'Opened',0,0,0,0,0,0,0,0,0.000000,345678)
panic: Error 1110: Column 'purchase_id' specified twice

I try to investigate it and find that it's beacuse of default value. If I remove it, the program will work correctly. 

Can anyone solve it? or if I have time I will try to fix it too.

### PR DESCRIPTION
**Pull request by developerdong**
… (fix #3670)

- [x] Do only one thing
- [x] Non breaking API changes
- [x] Tested

### What did this pull request do?

When someone sets a field having default tag, the field will appear twice in the INSERT clause, which leads to the error mentioned above.

### User Case Description

Sometimes I set a field actively and explicitly in a struct, but sometimes not. I want to make the field set with the default value specified by the `default` tag.

### CODE REVIEW

**Comment by jinzhu** [comment]
Can you add some tests?

**Comment by developerdong** [comment]
> Can you add some tests?

OK, please wait patiently. I'm a little busy these days.

**Comment by developerdong** [comment]
@jinzhu Hi, I force-pushed to the branch, because I may find the root cause for that error. I fix the error in a new way, and add a new test. My code can pass all the tests, while the master code can pass all the tests except for the newly added test by me.

**Review by daheige — APPROVED** [review]

**Review by daheige — APPROVED** [review]

**Comment by jinzhu** [comment]
doesn't really make sense to me, `default:1` as primary key won't works? or maybe you can turn off the autoincrement tag for the field.

**Comment by developerdong** [comment]
> doesn't really make sense to me, `default:1` as primary key won't works? or maybe you can turn off the autoincrement tag for the field.

The key reason is that the autoincrement tag's default value is `false`, right? But if I or someone else doesn't explicitly set the tag, the code fragment I mentioned above will set `field.AutoIncrement` to `true`, which is weird, inconsistent, and is not mentioned in the document online. I think this is a critical error, maybe we can fix it in another way, or at least tell people in the document.

**Comment by daheige** [comment]
Support what you said, at least let users understand the meaning here.


------------------ Original ------------------
From: Zhibin Dong ***@***.***&gt;
Date: Mon,May 31,2021 3:05 PM
To: go-gorm/gorm ***@***.***&gt;
Cc: heige ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [go-gorm/gorm] Tag `default` leads to the error `Error 1110: Column specified twice`… (#4389)





  
doesn't really make sense to me, default:1 as primary key won't works? or maybe you can turn off the autoincrement tag for the field.
  
The key reason is that the autoincrement tag's default value is false, right? But if I or someone else doesn't explicitly set the tag, the code fragment I mentioned above will set field.AutoIncrement to true, which is weird, inconsistent, and is not mentioned in the document online. I think this is a critical error, maybe we can fix it in another way, or at least tell people in the document.

**Pull request closed without merging**
