### PR TITLE
preload null judgment

### PR DESCRIPTION
**Pull request by 0fv**
when using count contain preload，will get panic message

### CODE REVIEW

**Comment by huacnlee** [comment]
Need a test for cover this.

**Comment by 0fv** [comment]
Added

**Comment by jinzhu** [comment]
Hi @0fv 

In this case, I think we should return an error, the `Preload` doesn't works as expected.

**Comment by 0fv** [comment]
> Hi @0fv
> 
> In this case, I think we should return an error, the `Preload` doesn't works as expected.

In practice,something like page load,sometime need load total count first, when count equal 0,no need call Find function,and after count need add limit and offset get correct page.Here is  my example

```go
type Page struct {
	Page  int
	Limit int
	Total int64
}

func (p *Page) LoadPage(db *gorm.DB, data interface{}) error {
	err := db.Count(&p.Total).Error
	if err != nil {
		return err
	}
	if p.Total == 0 {
		return nil
	}
	offset := (p.Page - 1) * p.Limit
	return db.Offset(offset).Limit(p.Limit).Find(data).Error
}
```

**Review by daheige — APPROVED** [review]

**Comment by jinzhu** [comment]
maybe consider another way to wrap it, ignore the error silently doesn't sound correct.

**Comment by daheige** [comment]
@jinzhu,support what you said.



发自我的iPhone


------------------ Original ------------------
From: Jinzhu ***@***.***&gt;
Date: Mon,Nov 29,2021 9:27 AM
To: go-gorm/gorm ***@***.***&gt;
Cc: heige ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [go-gorm/gorm] preload null judgment (PR #4833)





 
maybe consider another way to wrap it, ignore the error silently doesn't sound correct.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request closed without merging**
