### PR TITLE
feature(finisher_api): add Exists method

### PR DESCRIPTION
**Pull request by demoManito**
- [x] Do only one thing
- [x] Non breaking API changes
- [x] Tested

### CODE REVIEW

**Comment by demoManito** [comment]
Hi, can I add this method? If so, is it reasonable to add it this way, or should it be placed in the driver?

**Comment by jinzhu** [comment]
Maybe we should place it in a helper package, keeping GORM itself clean and avoiding adding too much API directly.

**Comment by demoManito** [comment]
> Maybe we should place it in a helper package, keeping GORM itself clean and avoiding adding too much API directly.

Do you mean the helper package under the go-gorm organization? @jinzhu

**Comment by jinzhu** [comment]
For now, we probably won’t maintain an additional helper package. It could be placed in a separate third-party library for the time being.

**Comment by demoManito** [comment]
> For now, we probably won’t maintain an additional helper package. It could be placed in a separate third-party library for the time being.

ok

**Pull request closed without merging**
