### PR TITLE
add dynamic tableName support

### PR DESCRIPTION
**Pull request by wuxq**
Add Dynamic TableName Support

### CODE REVIEW

**Comment by jinzhu** [comment]
Hi @wuxq 

Which is not supported intentionally, which cause lots of misuses

**Comment by jinzhu** [comment]
You can use `Scopes` for dynamic table name support.

**Comment by wuxq** [comment]
Scopes can't supported in  "join" or "Association"

**Comment by wuxq** [comment]
@jinzhu 
Thx  your reply.

But  Scopes can't supported  when use "join" or "Association"

Is there any other solution in this situation ?

**Pull request closed without merging**
