### PR TITLE
Update and Delete returning preload

### PR DESCRIPTION
**Pull request by FrancoLiberali**
- [x] Do only one thing
- [x] Non breaking API changes
- [x] Tested

### What did this pull request do?

Be able to do preloading with an UPDATE or DELETE that does RETURNING

### CODE REVIEW

**Comment by saeidee** [comment]
@FrancoLiberali thanks for your contribution, I see your point of adding it for the Returning clause case but not sure if it is logical to add it for update & delete generally.

**Comment by FrancoLiberali** [comment]
@saeidee In the case of not adding a returning, the preload would not affect the executed queries at all, since there is no preload to preload on. Prube:
Code:

    var result User

	log.Println("returning but empty results")
	if err := db.Model(&result).Where("name = ?", "not_exists").Clauses(clause.Returning{}).Preload("Account").Update("name", "order_name").Error; err != nil {
		log.Fatalln(err)
	}

	log.Println("no returning with empty results")
	if err := db.Model(&result).Where("name = ?", "not_exists").Preload("Account").Update("name", "order_name").Error; err != nil {
		log.Fatalln(err)
	}

	log.Println("no returning with not empty results")
	user := &User{Name: "exists"}
	if err := db.Create(user).Error; err != nil {
		log.Fatalln(err)
	}
	if err := db.Create(&Account{Name: "account", UserID: user.ID}).Error; err != nil {
		log.Fatalln(err)
	}
	if err := db.Model(&result).Where("name = ?", "exists").Preload("Account").Update("name", "exists").Error; err != nil {
		log.Fatalln(err)
	}
	log.Println(result)

	log.Println("returning with not empty results")
	if err := db.Model(&result).Where("name = ?", "exists").Clauses(clause.Returning{}).Preload("Account").Update("name", "exists").Error; err != nil {
		log.Fatalln(err)
	}
	log.Println(result)

Result:

returning but empty results
[0.669ms] [rows:0] UPDATE `users` SET `name`="order_name" WHERE name = "not_exists" RETURNING *

no returning with empty results
[0.153ms] [rows:0] UPDATE `users` SET `name`="order_name" WHERE name = "not_exists"

no returning with not empty results
[8.350ms] [rows:1] INSERT INTO `users` (`name`) VALUES ("exists") RETURNING `id`
[5.060ms] [rows:1] INSERT INTO `accounts` (`name`,`user_id`) VALUES ("account",2) RETURNING `id`
[0.235ms] [rows:2] UPDATE `users` SET `name`="exists" WHERE name = "exists"

{0 exists {0  0}}

returning with not empty results
[0.081ms] [rows:1] SELECT * FROM `accounts` WHERE `accounts`.`user_id` = 1
[0.121ms] [rows:1] INSERT INTO `accounts` (`name`,`user_id`,`id`) VALUES ("account",1,1) ON CONFLICT (`id`) DO UPDATE SET `user_id`=`excluded`.`user_id` RETURNING `id`
[0.729ms] [rows:1] UPDATE `users` SET `name`="exists" WHERE name = "exists" RETURNING *

{1 exists {1 account 1}}

**Review by a631807682 — COMMENTED** [review]
Can you describe why update statements need to use preload? In my understanding, they are not used together.

**Comment by jinzhu** [comment]
Preload is not designed works with Delete and Update, so going to close this pr. thank you for your contribution

**Pull request closed without merging**
