### PR TITLE
Add NewDB as a Shortcut Call

### PR DESCRIPTION
**Pull request by vzool**
- [x] Do only one thing
- [x] Non breaking API changes
- [x] Tested

### What did this pull request do?

Restore old New from v1 to be available in v2  as a shortcut call which is using new way of NewDB

### User Case Description

Current usage is very long, I used all over the application points.
```golang
// Current
db.Session(&gorm.Session{NewDB: true})
// Proposed
db.NewDB()
```

### CODE REVIEW

**Comment by jinzhu** [comment]
sorry, but not going to merge.

**Comment by jinzhu** [comment]
in most cases, this `db.Session(&gorm.Session{NewDB: true})` in not necessary, if you use it a lot, maybe there are something wrong in your code.

**Comment by vzool** [comment]
> in most cases, this `db.Session(&gorm.Session{NewDB: true})` in not necessary, if you use it a lot, maybe there are something wrong in your code.

In fact, I disagree. Because, if some use it inside HTTP handler with one database connection shared across many handlers like this:

```golang
// AccountIndex Handler
func AccountIndex(db *gorm.DB) gin.HandlerFunc {
	return func(ctx *gin.Context) {
                db = db.New() // Clear old query conditions from last call
                // ...
        }
}
```
Always they will need to call "**New**" because all HTTP handlers are shared one database connection.
Even, there are some interconnected logic needs "**New**" function to be called as well.
I hope that you may reconsider this PR again.
Thanks for this nice library <3

**Comment by jinzhu** [comment]
//  Clear old query conditions from last call

this is not necessary, check out https://gorm.io/docs/method_chaining.html#Method-Chain-Safety-Goroutine-Safety for details

**Pull request closed without merging**
