### PR TITLE
[#6372] Fixed nullable constraint bug for columns during auto migration

### PR DESCRIPTION
**Pull request by wookie0**
- [x] Do only one thing
- [x] Non breaking API changes
- [x] Tested

### What did this pull request do?

Fix nullable constraint bug for columns during auto migration.

* issue
  * #6372
  * https://github.com/go-gorm/gorm/issues/5643
* comment : https://github.com/go-gorm/gorm/issues/6372#issuecomment-2461541564

### User Case Description

TBD.

### CODE REVIEW

**Review by daheige — APPROVED** [review]

**Review by a631807682 — COMMENTED** [review]
Can you add some tests?

**Review by daheige — APPROVED** [review]
Good!

**Comment by wookie0** [comment]
@a631807682 @daheige 
I did add test case at the end. Because some of previous test failed. I didn't know what is problem. (sql-server env sync issue..? omg...)

**Comment by wookie0** [comment]
@a631807682 @daheige
I did add test case in the previous built test function.
But some checks were not successful, I saw the CI log. But I can't find what problem is. I think test code I added is not cause. any help??

**Comment by a631807682** [comment]
> @a631807682 @daheige I did add test case in the previous built test function. But some checks were not successful, I saw the CI log. But I can't find what problem is. I think test code I added is not cause. any help??
> 
> +) Also, test failed in master branch at local env.

refer to https://github.com/go-gorm/sqlserver/pull/134

upgrade gorm.io/driver/sqlserver to v1.5.4

**Comment by wookie0** [comment]
@a631807682 
Nice! Everything works perfect.
Thanks!!

**Review by a631807682 — APPROVED** [review]

**Comment by chandratripmp** [comment]
hi @jinzhu @daheige @a631807682, which version will this PR be included in?

**Pull request merged**
