### PR TITLE
refactor: part 2 of distinguish between Unique and UniqueIndex

### PR DESCRIPTION
**Pull request by black-06**
- [X] Do only one thing
- [X] Non breaking API changes
- [X] Tested

### What did this pull request do?

It's part 2 of #6386 which is the part of rollback, see https://github.com/go-gorm/gorm/pull/6386#issuecomment-1820049165.

It will also fix the ci.

But note that it depends on 
- https://github.com/go-gorm/mysql/pull/123
- https://github.com/go-gorm/postgres/pull/195
- https://github.com/go-gorm/sqlite/pull/156
- https://github.com/go-gorm/sqlserver/pull/106

After the above requests is merged, this pr still needs to update tests/go.mod to the corresponding commit id.

### CODE REVIEW

**Comment by saeidee** [comment]
To unblock new PRs, can we just resolve the CI tests issue in a dedicated PR and then decide/proceed on merging this new feature?

**Comment by black-06** [comment]
I have tested this mr with the above dependency, and it is OK.

Then we need to merge the driver mrs , and update test/go.mod here.

@jinzhu

**Comment by black-06** [comment]
My God, I tested it as test/docker-composite.yml, and it missed mysql 5.6

**Comment by jinzhu** [comment]
> My God, I tested it as test/docker-composite.yml, and it missed mysql 5.6

This is the benefit of our CI, to catch oversights in our daily development ;)

**Comment by black-06** [comment]
What a thrilling day, now we have fixed it 😭

**Pull request merged**
