### PR TITLE
prepare_stmt add ctx

### PR DESCRIPTION
**Pull request by LanLanBoom**
- [x] Do only one thing
- [x] Non breaking API changes
- [x] Tested

### What did this pull request do?

Context are lost in PreparedStmtDB and PreparedStmtTX functions, using context.Backgroud instead.  

This pull request fixed this problem.

### User Case Description

PreparedStmt insert, update, delete tested.

PreparedStmtTX insert, update, delete tested.

### CODE REVIEW

**Comment by jinzhu** [comment]
Hi, we don't include the context in the API on purpose,  so we can still cache the statement even it is a timeout context

Thank you for your PR anyway.

**Comment by jinzhu** [comment]
does it cause any issue for you?

**Comment by LanLanBoom** [comment]
> does it cause any issue for you?

yes, we are developing a mysql driver, wrapped around github.com/go-sql-driver/mysql with some logic packed, which relies on the ctx param being passed around.  

I think caching the statement even it is a timeout context is a rare case with little performance improvement.  However ctx passed arount is vital for extensibility. 

Perhaps passing arount ctx is more important, considering code extensibility?

**Comment by jinzhu** [comment]
https://github.com/go-gorm/gorm/commit/9b0ad4730f16d6ac7cf18d1aa42d74714959745b

merged, thank you for your pull request

**Pull request closed without merging**
