### PR TITLE
Fix URL in README.md

### PR DESCRIPTION
**Pull request by adi69**
- [x] Do only one thing
- [x] Non breaking API changes
- [x] Tested

### What did this pull request do?

The docs URLs are stale and still point to v1. This change fixes the URL to point to v2 docs.

### CODE REVIEW

**Comment by jinzhu** [comment]
Thank you for your PR, we will change v2.gorm.io to gorm.io after the release

**Comment by llh4github** [comment]
`https://v2.gorm.io` is currently unavailable, when will it be open?

**Comment by jinzhu** [comment]
Please visit cn.gorm.io or https://gorm.gitee.io/

**Comment by jinzhu** [comment]
btw, https://v2.gorm.io works for me.

**Pull request closed without merging**
