### PR TITLE
embedded field relationship schema do not contain relations

### LINKED ISSUE #3964: Schema in Relationship is different from the model
## GORM Playground Link

https://github.com/go-gorm/playground/pull/252

## Description

Due to the schema mismatch, the preload  will fail, because schema on Relationship do not have Relations

### PR DESCRIPTION
**Pull request by wenerme**
- [x] Do only one thing
- [x] Non breaking API changes
- [x] Tested

### What did this pull request do?

add current schema to cacheStore when ParseField

### User Case Description
fix #3964

### CODE REVIEW

**Comment by wenerme** [comment]
works for two levels, deeper relation still not exists.

**Comment by wenerme** [comment]
also tested against https://github.com/go-gorm/playground/pull/252

**Comment by wenerme** [comment]
this fix only works for small entity graph, large entity graph will cause supper slow parse, because too many dup fields to parse.

**Comment by jinzhu** [comment]
Fixed, thank you for your report and PR

**Pull request closed without merging**
