### PR TITLE
Optimize: utils.Contains applicable to more types

### PR DESCRIPTION
**Pull request by demoManito**
- [x]  Do only one thing
- [x] Non breaking API changes
- [x] Tested

### What did this pull request do?
I think the utils methods under utils should face more types than [] string

### User Case Description
refer to test cases

### CODE REVIEW

**Comment by a631807682** [comment]
I don't think it makes sense, and reflect will have performance issues. If this method name is causing you to misunderstand, I think it can be changed to `ContainsString`

**Comment by demoManito** [comment]
> I don't think it makes sense, and reflect will have performance issues. If this method name is causing you to misunderstand, I think it can be changed to `ContainsString`

I don't think so. The methods of the tool class should be more widely used. If they are not the methods of the tool class, there is no problem. Moreover, I have benchmarked the places I use, and the performance difference is not obvious

**Comment by a631807682** [comment]
```go
var ss = []string{"1", "2", "3", "4", "5"}
var s = "5"

func BenchmarkContainsString(b *testing.B) {
	for i := 0; i < b.N; i++ {
		ContainsString(ss, s)
	}
}

func BenchmarkContainsReflect(b *testing.B) {
	for i := 0; i < b.N; i++ {
		ContainsReflect(ss, s)
	}
}

func ContainsString(elems []string, elem string) bool {
	for _, e := range elems {
		if elem == e {
			return true
		}
	}
	return false
}

func ContainsReflect(elems interface{}, elem interface{}) bool {
	reflectValue := reflect.ValueOf(elems)
	if reflectValue.Kind() != reflect.Slice && reflectValue.Kind() != reflect.Array {
		return false
	}

	for i := 0; i < reflectValue.Len(); i++ {
		if reflectValue.Index(i).Interface() == elem {
			return true
		}
	}
	return false
}

```
go version go1.19 darwin/arm64
```
BenchmarkContainsString-8       91242894                12.43 ns/op
BenchmarkContainsReflect-8       6928802               170.1 ns/op
```

**Comment by jinzhu** [comment]
Not going to merge this PR, as seems this is not a necessary change for GORM.

**Comment by demoManito** [comment]
> ```go
> var ss = []string{"1", "2", "3", "4", "5"}
> var s = "5"
> 
> func BenchmarkContainsString(b *testing.B) {
> 	for i := 0; i < b.N; i++ {
> 		ContainsString(ss, s)
> 	}
> }
> 
> func BenchmarkContainsReflect(b *testing.B) {
> 	for i := 0; i < b.N; i++ {
> 		ContainsReflect(ss, s)
> 	}
> }
> 
> func ContainsString(elems []string, elem string) bool {
> 	for _, e := range elems {
> 		if elem == e {
> 			return true
> 		}
> 	}
> 	return false
> }
> 
> func ContainsReflect(elems interface{}, elem interface{}) bool {
> 	reflectValue := reflect.ValueOf(elems)
> 	if reflectValue.Kind() != reflect.Slice && reflectValue.Kind() != reflect.Array {
> 		return false
> 	}
> 
> 	for i := 0; i < reflectValue.Len(); i++ {
> 		if reflectValue.Index(i).Interface() == elem {
> 			return true
> 		}
> 	}
> 	return false
> }
> ```
> 
> go version go1.19 darwin/arm64
> 
> ```
> BenchmarkContainsString-8       91242894                12.43 ns/op
> BenchmarkContainsReflect-8       6928802               170.1 ns/op
> ```

image
for real implementation, the changes here will not affect performance

**Comment by demoManito** [comment]
> Member

OK, thank you for your reply

**Pull request closed without merging**
