### PR TITLE
new feature.skip hook by name

### PR DESCRIPTION
**Pull request by Sivyer9303**
- [x] Do only one thing
- [x] Non breaking API changes
- [x] Tested

### What did this pull request do?

Add new feature. see #4562

### User Case Description

see #4562

### CODE REVIEW

**Review by daheige — APPROVED** [review]

**Comment by Sivyer9303** [comment]
there is some bugs,i'll fix it.please dont merge before i fix.

**Comment by daheige** [comment]
ok，you can continue to submit, then run down the unit test, and then we merge after passing.



发自我的iPhone


------------------ Original ------------------
From: Sivyer ***@***.***&gt;
Date: Tue,Aug 3,2021 6:59 PM
To: go-gorm/gorm ***@***.***&gt;
Cc: heige ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [go-gorm/gorm] new feature.skip hook by name (#4574)





 
there is some bugs,i'll fix it.please dont merge before i fix.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Sivyer9303** [comment]
please review again.

**Comment by Sivyer9303** [comment]
i refactor callbacks.RegisterDefaultCallbacks with extract hook names to constants and move them to gorm package.
Original skipHook had replaced by Statement.CanSkip and Statement.ShouldSkip.These two func will not skip core hook,such as Update hook, skip all hook when statement.skiphook is true or skip specific hook by hook name.

**Comment by daheige** [comment]
ok，greate job.


------------------ Original ------------------
From: Sivyer ***@***.***&gt;
Date: Wed,Aug 4,2021 8:46 PM
To: go-gorm/gorm ***@***.***&gt;
Cc: heige ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [go-gorm/gorm] new feature.skip hook by name (#4574)





 
i refactor callbacks.RegisterDefaultCallbacks with extract hook names to constants and move them to gorm package.
 Original skipHook had replaced by Statement.CanSkip and Statement.ShouldSkip.These two func will not skip core hook,such as Update hook, skip all hook when statement.skiphook is true or skip specific hook by hook name.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by daheige** [comment]
ok


------------------ Original ------------------
From: Sivyer ***@***.***&gt;
Date: Wed,Aug 4,2021 8:38 PM
To: go-gorm/gorm ***@***.***&gt;
Cc: heige ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [go-gorm/gorm] new feature.skip hook by name (#4574)





 
please review again.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by daheige** [comment]
@jinzhu

**Comment by jinzhu** [comment]
sorry, but don't really want to support this. maybe use context value or settings in hooks method to judge execute it or not.

**Comment by Sivyer9303** [comment]
> sorry, but don't really want to support this. maybe use context value or settings in hooks method to judge execute it or not.

It's ok, thanks for reply

**Pull request closed without merging**
