### PR TITLE
feat: add `When`

### PR DESCRIPTION
**Pull request by flc1125**
- [x] Do only one thing
- [x] Non breaking API changes
- [x] Tested

### What did this pull request do?

I added a `When` to implement the logic when conditions exist

### User Case Description

```go
var age = 16

db.When(age > 18, func (db *gorm.DB) {
    return db.Where("show = ?", 1)
}).Where(...)

```

### CODE REVIEW

**Review by a631807682 — COMMENTED** [review]
Thanks for your PR, but it doesn't seem necessary, you can do it with `Scope`

**Comment by flc1125** [comment]
> Thanks for your PR, but it doesn't seem necessary, you can do it with `Scope`

But when I'm associated with the business context, I need to add a lot of lines to solve this problem, in this way, I think it's more convenient.

**Comment by flc1125** [comment]
> Thanks for your PR, but it doesn't seem necessary, you can do it with `Scope`

For Example:

```go
// When use `When`
DB.Where("age >= ?", 10).
    When(request.Get("name") != "", func(db *gorm.DB) *gorm.DB {
        return db.Where("name = ?", request.Get("name"))
    }).First(&user)

// When not use `When`
DB.Where("age >= ?", 10)

if request.Get("name") != "" {
    DB = DB.Where("name = ?", request.Get("name"))
}

DB.First(&user)
```

**Comment by a631807682** [comment]
https://gorm.io/docs/scopes.html#content-inner
```go
func When(condition bool, fn func(*gorm.DB) *gorm.DB) func(*gorm.DB) *gorm.DB {
	if condition {
		return fn
	}

	return func(d *gorm.DB) *gorm.DB {
		return d
	}
}

DB.Scopes(When(age > 18, func(db *gorm.DB) *gorm.DB {
		return db.Where("show = ?", 1)
})).Where(...)
```

**Comment by flc1125** [comment]
> I think there is no difference, and scope can be used in more scenarios. https://gorm.io/docs/scopes.html#content-inner
> 
> ```go
> func When(condition bool, fn func(*gorm.DB) *gorm.DB) func(*gorm.DB) *gorm.DB {
> 	if condition {
> 		return fn
> 	}
> 
> 	return func(d *gorm.DB) *gorm.DB {
> 		return d
> 	}
> }
> 
> DB.Scopes(When(age > 18, func(db *gorm.DB) *gorm.DB {
> 		return db.Where("show = ?", 1)
> })).Where(...)
> ```

The purpose of the framework is to make it easier for developers to use it, and some common and convenient method can be introduced into the framework so that other projects don't have to copy it every time.

And again, this is a function that a lot of people around you want to have.

Hopefully it will go through the merger.😁😁

**Comment by a631807682** [comment]
Sorry, we must maintain the necessity of the API to ensure that it will not be unmaintainable due to the expansion of supported features.
Of course, we also welcome users to expand it, including drivers, plugins, clauses, tools or others, we will add links to good projects, and we will also evaluate and accept new projects into the go-gorm organization

**Comment by flc1125** [comment]
> Sorry, we must maintain the necessity of the API to ensure that it will not be unmaintainable due to the expansion of supported features. Of course, we also welcome users to expand it, including drivers, plugins, clauses, tools or others, we will add links to good projects, and we will also evaluate and accept new projects into the go-gorm organization
> 
> https://gorm.io/community.html#Open-Sources

Okay, surprisingly, I think gorm has a long way to go in terms of ease of use.

**Comment by jinzhu** [comment]
I think the `When` API is just a sugar method, and too many sugars are bad for project quality & maintainability.

So we should be very careful with any new APIs, and only add them if it helps a lot to make users write better code.


For this feature, I would suggest users extract business logic like https://gorm.io/docs/scopes.html#Pagination , for your application, it might be written like the following code:

```go
func Allowed(user User) func(*gorm.DB) *gorm.DB {
   if user.Age > 18 || user.Role == "admin" { 
       return func(tx *gorm.DB) *gorm.DB {
           return tx.Where("show = ?", 1)
      }
   }

   return func(tx *gorm.DB) *gorm.DB {
       return tx.Where("show = ?", 0)
   }
}

db.Where(Allowed(user)).Find(&articles)
```

**Comment by flc1125** [comment]
> I think the `When` API is just a sugar method, and too many sugars are bad for project quality & maintainability.
> 
> So we should be very careful with any new APIs, and only add them if it helps a lot to make users write better code.
> 
> For this feature, I would suggest users extract business logic like https://gorm.io/docs/scopes.html#Pagination , for your application, it might be written like the following code:
> 
> ```go
> func Allowed(user User) func(*gorm.DB) *gorm.DB {
>    if user.Age > 18 || user.Role == "admin" { 
>        return func(tx *gorm.DB) *gorm.DB {
>            return tx.Where("show = ?", 1)
>       }
>    }
> 
>    return func(tx *gorm.DB) *gorm.DB {
>        return tx.Where("show = ?", 0)
>    }
> }
> 
> db.Scopes(Allowed(user)).Find(&articles)
> ```

Get, thanks for your time.

Perhaps `when` is better loaded in an extended form.

**Pull request closed without merging**
