### PR TITLE
feat: add tidb integration test cases

### PR DESCRIPTION
**Pull request by Icemap**
- [x] Do only one thing
- [x] Non breaking API changes
- [x] Tested

### What did this pull request do?

Add TiDB integration test cases. And skip some features that TiDB is not implicated.
This PR is based on https://github.com/go-gorm/mysql/pull/105, need to wait for that to merge.

### CODE REVIEW

**Comment by Icemap** [comment]
This PR request https://github.com/go-gorm/mysql/pull/105 merged. Please hold until it's merged.

**Comment by Icemap** [comment]
All tests passed. PTAL. @jinzhu

**Review by jinzhu — APPROVED** [review]

**Comment by jinzhu** [comment]
Maybe you can add how to connect tidb to the help document. https://github.com/go-gorm/gorm.io/blob/master/pages/docs/connecting_to_the_database.md

**Comment by Icemap** [comment]
THX, I'll be working on it.

**Comment by Icemap** [comment]
The document PR is: https://github.com/go-gorm/gorm.io/pull/638

**Pull request merged**
